resources:
  - url: http://127.0.0.1:5000/spu-trash-collection-card.js
    type: module
views:
  - cards:
      - type: custom:spu-trash-collection-card
        name: SPU Trash Collection Card Development
        entity: sun.sun
        test_gui: true
